# Generated by Django 6.0.3 on 2026-07-29 02:52

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Carrera')),
                ('codigo', models.CharField(max_length=6, unique=True, verbose_name='Código')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('semipresencial', 'Semipresencial'), ('online', 'Online')], max_length=20, verbose_name='Modalidad')),
                ('duracion_semestres', models.PositiveSmallIntegerField(default=8, verbose_name='Duración en semestres')),
                ('cupo_maximo', models.PositiveIntegerField(default=40, verbose_name='Cupo máximo')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombres y apellidos')),
                ('cedula', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener exactamente 10 dígitos numéricos', regex='^\\d{10}$')], verbose_name='Cédula')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('fecha_ingreso', models.DateField(default=datetime.date.today, verbose_name='Fecha de ingreso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('egresado', 'Egresado'), ('retirado', 'Retirado')], default='activo', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('carrera_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='academico.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Número de matrícula')),
                ('periodo', models.CharField(choices=[('2026-01', '2026-01'), ('2026-02', '2026-02')], max_length=7, verbose_name='Periodo')),
                ('asignatura', models.CharField(max_length=100, verbose_name='Asignatura')),
                ('creditos', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='Créditos')),
                ('costo_credito', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=6, verbose_name='Costo por crédito')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada')], default='borrador', max_length=20, verbose_name='Estado')),
                ('observacion', models.TextField(blank=True, verbose_name='Observación')),
                ('estudiante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='academico.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
